[build]
  command = "pip install -r requirements.txt && uvicorn api.main:app --host 0.0.0.0 --port 8888"
  functions = "api"

[functions]
  directory = "functions"

[[redirects]]
from = "/*"
to = "/.netlify/functions/api"
status = 200
